import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    itemName: 'Mercurial XI',
    brand: 'Nike',
    vendor: 'Acme Sports',
    imagePath:
      'https://images.unsplash.com/photo-1624006389438-c03488175975?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fHNuZWFrZXJzfGVufDB8MnwwfHw%3D&auto=format&fit=crop&w=400&q=60',
    rating: 3,
    totalRatings: 134,
    currentPrice: 595,originalPrice: 700,
    categoryName: 'formals',
    color: 'black',
    isFeatured: false,
    Stock: 37,
    isFreeDelivery: false,
    isBestSeller: true,
    offerPercentage: 15,
    item: 'Shoe',
    weight: '213 gms',
  },
  {
    _id: uuid(),
    itemName: 'Skyline',
    brand: 'Puma',
    vendor: 'Royal Sports',
    imagePath:
      'https://images.unsplash.com/photo-1624006389438-c03488175975?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fHNuZWFrZXJzfGVufDB8MnwwfHw%3D&auto=format&fit=crop&w=400&q=60',
    rating: 2,
    totalRatings: 11,
    currentPrice: 945,originalPrice: 1350,
    categoryName: 'sports',
    color: 'blue',
    isFeatured: true,
    Stock: 35,
    isFreeDelivery: true,
    isBestSeller: false,
    offerPercentage: 30,
    item: 'Shoe',
    weight: '214 gms',
  },
  {
    _id: uuid(),
    itemName: 'Venom',
    brand: 'Adidas',
    vendor: 'Digit Inc',
    imagePath:
      'https://images.unsplash.com/photo-1646215279503-7dd99848a8ee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mzh8fGJvb3RzfGVufDB8MnwwfHw%3D&auto=format&fit=crop&w=400&q=60',
    rating: 5,
    totalRatings: 67,
    currentPrice: 180,originalPrice: 200,
    categoryName: 'sports',
    color: 'green',
    isFeatured: false,
    Stock: 45,
    isFreeDelivery: false,
    isBestSeller: false,
    offerPercentage: 10,
    item: 'Shoe',
    weight: '321 gms',
  },
  {
    _id: uuid(),
    itemName: 'Superfly',
    brand: 'Nike',
    vendor: 'Vitaly Sports',
    imagePath:
      'https://images.unsplash.com/photo-1529810313688-44ea1c2d81d3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fHNwb3J0cyUyMHNob2VzfGVufDB8MnwwfHw%3D&auto=format&fit=crop&w=400&q=60',
    rating: 5,
    totalRatings: 90,
    currentPrice: 338,originalPrice: 450,
    categoryName: 'sneakers',
    color: 'black',
    isFeatured: false,
    Stock: 89,
    isFreeDelivery: true,
    isBestSeller: true,
    offerPercentage: 25,
    item: 'Shoe',
    weight: '270 gms',
  },
  {
    _id: uuid(),
    itemName: 'Spectral',
    brand: 'Sega',
    vendor: 'Runin Shoes',
    imagePath:
      'https://images.unsplash.com/photo-1491553895911-0055eca6402d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c2Nob29sJTIwc2hvZXN8ZW58MHwyfDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60',
    rating: 4,
    totalRatings: 70,
    currentPrice: 760,originalPrice: 950,
    categoryName: 'boots',
    color: 'black',
    isFeatured: true,
    Stock: 40,
    isFreeDelivery: true,
    isBestSeller: false,
    offerPercentage: 20,
    item: 'Shoe',
    weight: '280 gms',
  },
  {
    _id: uuid(),
    itemName: 'Rosario XX',
    brand: 'Adidas',
    vendor: 'Rio Calcio',
    imagePath:
      'https://images.unsplash.com/photo-1646215279503-7dd99848a8ee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mzh8fGJvb3RzfGVufDB8MnwwfHw%3D&auto=format&fit=crop&w=400&q=60',
    rating: 5,
    totalRatings: 123,
    currentPrice: 1575,originalPrice: 1750,
    categoryName: 'sneakers',
    color: 'black',
    isFeatured: true,
    Stock: 56,
    isFreeDelivery: true,
    isBestSeller: true,
    offerPercentage: 10,
    item: 'Shoe',
    weight: '300 gms',
  },
  {
    _id: uuid(),
    itemName: 'Milan',
    brand: 'UnderArmor',
    vendor: 'Big Shoes',
    imagePath:
      'https://images.unsplash.com/photo-1529810313688-44ea1c2d81d3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fHNwb3J0cyUyMHNob2VzfGVufDB8MnwwfHw%3D&auto=format&fit=crop&w=400&q=60',
    rating: 2,
    totalRatings: 121,
    currentPrice: 360,originalPrice: 600,
    categoryName: 'boots',
    color: 'black',
    isFeatured: true,
    Stock: 89,
    isFreeDelivery: false,
    isBestSeller: false,
    offerPercentage: 40,
    item: 'Shoe',
    weight: '200 gms',
  },
  {
    _id: uuid(),
    itemName: 'Venom Evo',
    brand: 'Nike',
    vendor: 'Acme Sports',
    imagePath:
      'https://images.unsplash.com/photo-1581017316696-709bf1da2ed5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTB8fGhpa2luZyUyMHNob2VzfGVufDB8MnwwfHw%3D&auto=format&fit=crop&w=400&q=60',
    rating: 1,
    totalRatings: 78,
    currentPrice: 1350,originalPrice: 1500,
    categoryName: 'hiking',
    color: 'black',
    isFeatured: true,
    Stock: 50,
    isFreeDelivery: true,
    isBestSeller: true,
    offerPercentage: 10,
    item: 'Shoe',
    weight: '250 gms',
  },
  {
    _id: uuid(),
    itemName: 'Aggregor VM',
    brand: 'Agility',
    vendor: 'Acme Inc',
    imagePath:
      'https://images.unsplash.com/photo-1491553895911-0055eca6402d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c2Nob29sJTIwc2hvZXN8ZW58MHwyfDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60',
    rating: 5,
    totalRatings: 90,
    currentPrice: 280,originalPrice: 400,
    categoryName: 'hiking',
    color: 'black',
    isFeatured: true,
    Stock: 10,
    isFreeDelivery: false,
    isBestSeller: true,
    offerPercentage: 30,
    item: 'Shoe',
    weight: '250 gms',
  } , 
  {
    _id: uuid(),
    itemName: 'Uni AC3',
    brand: 'Nike',
    vendor: 'Royal Sports',
    imagePath:
      'https://images.unsplash.com/photo-1491553895911-0055eca6402d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c2Nob29sJTIwc2hvZXN8ZW58MHwyfDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60',
    rating: 4,
    totalRatings: 341,
    currentPrice:550,originalPrice: 1100,
    categoryName: 'hiking',
    color: 'black',
    isFeatured: true,
    Stock: 0,
    isFreeDelivery: true,
    isBestSeller: true,
    offerPercentage: 50,
    item: 'Shoe',
    weight: '260 gms',
  },
  {
    _id: uuid(),
    itemName: 'Joltion',
    brand: 'Pike',
    vendor: 'Nintendo',
    imagePath:
      'https://images.unsplash.com/photo-1491553895911-0055eca6402d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c2Nob29sJTIwc2hvZXN8ZW58MHwyfDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60',
    rating: 3,
    totalRatings: 167,
    currentPrice: 1805,originalPrice: 1900,
    categoryName: 'hiking',
    color: 'black',
    isFeatured: true,
    Stock: 12,
    isFreeDelivery: false,
    isBestSeller: true,
    offerPercentage: 5,
    item: 'Shoe',
    weight: '250 gms',
  }
];
